---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: build
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /console/frontend
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: build
    schedule:
      interval: monthly
    labels:
      - dependencies
    open-pull-requests-limit: 10
    groups:
      vueuse:
        patterns:
          - "@vueuse/*"
      vue:
        patterns:
          - "vue"
          - "vue-*"
      codemirror:
        patterns:
          - "@codemirror/*"
          - "@lezer/*"
      dev-dependencies:
        patterns:
          - "@volar/*"
          - "@vitest/*"
          - "vitest"
          - "eslint*"
          - "prettier*"
      typing:
        patterns:
          - "@types/*"
  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: build
    schedule:
      interval: weekly
    labels:
      - dependencies
