---
version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:3.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.8.1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - 127.0.0.1:9092:9093/tcp

  clickhouse:
    image: clickhouse/clickhouse-server:22.2
    depends_on:
      - kafka
    ports:
      - 127.0.0.1:8123:8123/tcp
      - 127.0.0.1:9000:9000/tcp

  # Authentik
  authentik:
    image: &authentik-image ghcr.io/goauthentik/server:2022.5.3
    command: server
    environment: &authentik-env
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: dummypassword
      AUTHENTIK_DISABLE_UPDATE_CHECK: "true"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: "true"
      AUTHENTIK_AVATARS: none
      AUTHENTIK_SECRET_KEY: dummykey
      AK_ADMIN_PASS: akadmin
      AK_ADMIN_TOKEN: aktoken
    ports:
      - 127.0.0.1:8999:9000/tcp
    depends_on:
      - authentik-postgresql
      - authentik-redis
      - authentik-worker
  authentik-postgresql:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=dummypassword
      - POSTGRES_USER=authentik
      - POSTGRES_DB=authentik
  authentik-redis:
    image: redis:alpine
  authentik-worker:
    image: *authentik-image
    command: worker
    environment: *authentik-env
