---
version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:3.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.8.1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
    depends_on:
      - zookeeper
    ports:
      - 9092:9092/tcp

  clickhouse:
    image: clickhouse/clickhouse-server:22.2
    ports:
      - 8123:8123/tcp
