---
site_name: Akvorado
site_dir: web/data
strict: true
use_directory_urls: false
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: "#008affff"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: "#008affff"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Montserrat
    code: Roboto Mono
  logo: assets/images/akvorado.svg
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Documentation:
      Design: design.md
      Installation: install.md
      Configuration: configuration.md
      Usage: usage.md
      Integration: integration.md
      Troubleshooting: troubleshooting.md
      Internals: internals.md

