---
services:
  geoip:
    build:
      context: .
      dockerfile: Dockerfile.ipinfo-geoipupdate
    environment:
      - IPINFO_TOKEN=a2632ea59736c7
      - IPINFO_DATABASES=country asn
      - UPDATE_FREQUENCY=48h
    volumes:
      - akvorado-geoip:/data
