---
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 127.0.0.1:9090
  - job_name: grafana
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
        filters:
          - name: label
            values:
              - com.docker.compose.project=akvorado
              - com.docker.compose.service=grafana
  - job_name: akvorado
    metrics_path: /api/v0/metrics
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
        filters:
          - name: label
            values:
              - com.docker.compose.project=akvorado
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: akvorado-(inlet|orchestrator|console)
        action: keep
      - source_labels: [__meta_docker_port_private]
        regex: 8080
        action: keep
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
        regex: akvorado-(.*)
        replacement: $1
