---
services:
  # main services
  zookeeper:
    image: bitnami/zookeeper:3.8
  kafka:
    image: bitnami/kafka:3.7
  redis:
    image: bitnami/redis:7.2
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
  traefik:
    image: traefik:2.6
  akvorado:
    image: ghcr.io/akvorado/akvorado:main

  # observability
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1

  # for tests
  srlinux:
    image: ghcr.io/nokia/srlinux:23.7.1
