---
name: Update flake.nix
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - console/frontend/package-lock.json
jobs:
  flake:
    name: Update hashs in flake.nix
    runs-on: ubuntu-latest
    concurrency:
      group: update-flake-nix
      cancel-in-progress: true
    steps:
      - name: Sleep a bit
        run: sleep 120
        if: ${{ github.event_name == 'push' }}
      - uses: actions/checkout@v4
        if: ${{ !cancelled() }}
      - uses: cachix/install-nix-action@v25
        if: ${{ !cancelled() }}
      - name: Update flake.nix
        run: nix run .#passthru.update
        if: ${{ !cancelled() }}
      - name: Push update
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.lock nix
          ! git commit -m "build: update flake.nix" || git push
        if: ${{ !cancelled() }}
      - run: exit 0
        if: ${{ cancelled() }}
